encoder_conf:
    main_conf:
      pos_wise_act_type: swish
      pos_enc_dropout_rate: 0.1
      conv_mod_act_type: swish
      dynamic_chunk_training: True
      short_chunk_threshold: 0.75
      short_chunk_size: 25
      num_left_chunks: 0
    input_conf:
      block_type: conv2d
      conv_size: 256
      subsampling_factor: 4
    body_conf:
    - block_type: conv1d
      output_size: 128
      kernel_size: 3
    - block_type: conv1d
      output_size: 256
      kernel_size: 2
    - block_type: conformer
      linear_size: 1024
      hidden_size: 256
      heads: 8
      dropout_rate: 0.1
      pos_wise_dropout_rate: 0.1
      att_dropout_rate: 0.1
      conv_mod_kernel_size: 31
      num_blocks: 14

# decoder related
decoder: rnn
decoder_conf:
    rnn_type: lstm
    num_layers: 2
    embed_size: 256
    hidden_size: 256
    dropout_rate: 0.1
    embed_dropout_rate: 0.1

# joint_network related
joint_network_conf:
  joint_space_size: 256
  joint_activation_type: "tanh"

# Multi-task learning
model_conf:
    fastemit_lambda: 0.0
    validation_nstep: 2
    transducer_weight: 1.0
    auxiliary_mtp_loss_weight: 1.0
    auxiliary_ctc_weight: 0.0
    auxiliary_ctc_dropout_rate: 0.0
    auxiliary_lm_loss_weight: 0.0
    auxiliary_lm_loss_smoothing: 0.05
    report_cer: True
    report_wer: True


# minibatch related
batch_type: sorted
batch_size: 64
valid_batch_size: 32
# optimization related
accum_grad: 1
grad_clip: 5
patience: 3
max_epoch: 40
val_scheduler_criterion:
    - valid
    - cer_transducer
best_model_criterion:
-   - valid
    - cer_transducer
    - min
early_stopping_criterion:
    - valid
    - cer_transducer
    - min
keep_nbest_models: 10

# NoamLR is deprecated. Use WarmupLR.
# The following is equivalent setting for NoamLR:
#
#    optim: adam
#    optim_conf:
#        lr: 10.
#    scheduler: noamlr
#    scheduler_conf:
#        model_size: 256
#        warmup_steps: 25000
#
optim: adam
optim_conf:
    lr: 0.0005
scheduler: warmuplr     # pytorch v1.1.0+ required
scheduler_conf:
    warmup_steps: 30000
num_att_plot: 0
specaug: specaug
specaug_conf:
    apply_time_warp: true
    time_warp_window: 5
    time_warp_mode: bicubic
    apply_freq_mask: true
    freq_mask_width_range:
    - 0
    - 30
    num_freq_mask: 2
    apply_time_mask: true
    time_mask_width_range:
    - 0
    - 40
    num_time_mask: 2
